### ISSUE TITLE
Can I use MySQL instead of SQLite?

### ISSUE THREAD

**Issue by THROFHR** [tulir/telethon-session-sqlalchemy#4]
Hello，I use MySQL instead of SQLite，I got an error

`sqlalchemy.exc.CompileError: (in table 'update_state', column 'session_id'): VARCHAR requires a length on dialect mysql`

Is there any solution?

**Comment by tulir** [comment]
I guess I need to add lengths to all the string columns in the database. I can try to fix it this weekend.

**Comment by tulir** [comment]
I haven't tested that yet, but you can already check if it works by installing directly from git (`pip install git+https://github.com/tulir/telethon-session-sqlalchemy.git#egg=alchemysession`)

**Comment by THROFHR** [comment]
OK
